# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161128_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgame',
            name='loaded_into_redshift',
            field=models.DateTimeField(null=True),
        ),
    ]
