# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20161128_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalgameplayer',
            old_name='deck_id',
            new_name='deck_id_legacy',
        ),
        migrations.AddField(
            model_name='globalgameplayer',
            name='deck_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Deck ID'),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='deck_id_legacy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deck ID (OLD)'),
        ),
    ]
