# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 03:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_intenum
import hearthstone.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0004_globalgame_tainted_decks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PegasusAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_hi', models.BigIntegerField(help_text='The region value from account hilo', verbose_name='Account Hi')),
                ('account_lo', models.BigIntegerField(help_text='The account ID value from account hilo', verbose_name='Account Lo')),
                ('region', django_intenum.IntEnumField(verbose_name=hearthstone.enums.BnetRegion)),
                ('battletag', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='globalgameplayer',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='pegasusaccount',
            unique_together=set([('account_hi', 'account_lo')]),
        ),
    ]
