# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_intenum
import hearthstone.enums


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170304_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgameplayer',
            name='pegasus_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.PegasusAccount'),
        ),
        migrations.AlterField(
            model_name='pegasusaccount',
            name='region',
            field=django_intenum.IntEnumField(choices=[(-1, 'REGION_UNINITIALIZED'), (0, 'REGION_UNKNOWN'), (1, 'REGION_US'), (2, 'REGION_EU'), (3, 'REGION_KR'), (4, 'REGION_TW'), (5, 'REGION_CN'), (40, 'REGION_LIVE_VERIFICATION'), (41, 'REGION_PTR_LOC'), (52, 'REGION_MSCHWEITZER_BN11'), (53, 'REGION_MSCHWEITZER_BN12'), (60, 'REGION_DEV'), (98, 'REGION_PTR')], validators=[django_intenum.IntEnumValidator(hearthstone.enums.BnetRegion)]),
        ),
    ]
