# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170304_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamereplay',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='globalgameplayer',
            name='account_hi',
        ),
        migrations.RemoveField(
            model_name='globalgameplayer',
            name='account_lo',
        ),
    ]
