# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20170404_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgameplayer',
            name='extra_turns',
            field=models.SmallIntegerField(help_text='Extra turns taken by the player this game (Time Warp).', null=True),
        ),
    ]
