# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_intenum
import hearthstone.enums


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_globalgameplayer_extra_turns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgame',
            name='game_type',
            field=django_intenum.IntEnumField(blank=True, choices=[(0, 'BGT_UNKNOWN'), (1, 'BGT_FRIENDS'), (2, 'BGT_RANKED_STANDARD'), (3, 'BGT_ARENA'), (4, 'BGT_VS_AI'), (5, 'BGT_TUTORIAL'), (6, 'BGT_ASYNC'), (9, 'BGT_CASUAL_STANDARD_NEWBIE'), (10, 'BGT_CASUAL_STANDARD_NORMAL'), (11, 'BGT_TEST1'), (12, 'BGT_TEST2'), (13, 'BGT_TEST3'), (16, 'BGT_TAVERNBRAWL_PVP'), (17, 'BGT_TAVERNBRAWL_1P_VERSUS_AI'), (18, 'BGT_TAVERNBRAWL_2P_COOP'), (30, 'BGT_RANKED_WILD'), (31, 'BGT_CASUAL_WILD'), (40, 'BGT_FSG_BRAWL_VS_FRIEND'), (41, 'BGT_FSG_BRAWL_PVP'), (42, 'BGT_FSG_BRAWL_1P_VERSUS_AI'), (43, 'BGT_FSG_BRAWL_2P_COOP')], null=True, validators=[django_intenum.IntEnumValidator(hearthstone.enums.BnetGameType)], verbose_name='Game type'),
        ),
        migrations.AlterField(
            model_name='globalgameplayer',
            name='pegasus_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.PegasusAccount'),
        ),
    ]
