# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20161015_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereplay',
            name='opponent_revealed_deck',
            field=models.ForeignKey(help_text="As much as is known of the opponent's starting deck list.", null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.Deck'),
        ),
    ]
