# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0014_auto_20161015_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortid', hsreplaynet.utils.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True, verbose_name='Short ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayListItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameReplay')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.PlayList')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='in_playlists', through='games.PlayListItem', to='games.GameReplay'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
