# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_gamereplay_opponent_revealed_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgameplayer',
            name='real_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Real name'),
        ),
    ]
