# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:26
from __future__ import unicode_literals

from django.db import migrations


DROP_IDX_GLOBALGAMEPLAYER_A6B33C88 = """
DROP INDEX games_globalgameplayer_name_a6b33c88_uniq;
"""


DROP_IDX_GLOBALGAMEPLAYER_CA45EDCA = """
DROP INDEX games_globalgameplayer_hero_id_ca45edca_like;
"""


class Migration(migrations.Migration):

	dependencies = [
		('games', '0017_auto_20161121_2217'),
	]

	operations = [
		migrations.RunSQL(
			DROP_IDX_GLOBALGAMEPLAYER_A6B33C88,
			None
		),
		migrations.RunSQL(
			DROP_IDX_GLOBALGAMEPLAYER_CA45EDCA,
			None
		),
	]
