# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:59
from __future__ import unicode_literals

from django.db import migrations


DROP_IDX_GAMREPLAY_EF930F0C = """
DROP INDEX games_gamereplay_shortid_ef930f0c_like;
"""


class Migration(migrations.Migration):

	dependencies = [
		('games', '0018_auto_20161122_0026'),
	]

	operations = [
		migrations.RunSQL(
			DROP_IDX_GAMREPLAY_EF930F0C,
			None
		),
	]
