# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 07:35
from __future__ import unicode_literals

import django.db.models.deletion
import django_intenum
import hearthstone.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booster_type', django_intenum.IntEnumField(enum=hearthstone.enums.Booster)),
                ('date', models.DateTimeField()),
                ('account_hi', models.BigIntegerField()),
                ('account_lo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('premium', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Card')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packs.Pack')),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='cards',
            field=models.ManyToManyField(through='packs.PackCard', to='cards.Card'),
        ),
        migrations.AddField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
