# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_intenum
import hearthstone.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booster_type', django_intenum.IntEnumField(choices=[(0, 'INVALID'), (1, 'CLASSIC'), (9, 'GOBLINS_VS_GNOMES'), (10, 'THE_GRAND_TOURNAMENT'), (11, 'OLD_GODS'), (17, 'FIRST_PURCHASE'), (18, 'SIGNUP_INCENTIVE'), (19, 'MEAN_STREETS'), (20, 'UNGORO')], validators=[django_intenum.IntEnumValidator(hearthstone.enums.Booster)])),
                ('date', models.DateTimeField()),
                ('account_hi', models.BigIntegerField()),
                ('account_lo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('premium', models.BooleanField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cards.Card')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='packs.Pack')),
            ],
        ),
        migrations.AddField(
            model_name='pack',
            name='cards',
            field=models.ManyToManyField(through='packs.PackCard', to='cards.Card'),
        ),
        migrations.AddField(
            model_name='pack',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
