# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 08:22
from __future__ import unicode_literals

import uuid

import django.core.validators
import django.db.models.deletion
import django_intenum
from django.db import migrations, models

import hsreplaynet.features.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djstripe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', django_intenum.IntEnumField(default=0, enum=hsreplaynet.features.models.FeatureStatus)),
                ('read_only', models.BooleanField(default=False)),
                ('rollout_percent', models.PositiveIntegerField(default=100, help_text='This may be set to a value lower than 100 to further restrict the user pool with access to this feature.', validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='FeatureInvite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_count', models.PositiveIntegerField(default=0, editable=False, help_text='The amount of times this invitation has been successfully used.')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 for unlimited')),
                ('expires', models.DateTimeField(blank=True, help_text='No longer valid after this date.', null=True)),
                ('coupon', models.CharField(blank=True, help_text='Redeem a Stripe Coupon', max_length=500)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, related_name='invites', to='features.Feature')),
                ('subscribe_to', models.ForeignKey(blank=True, help_text='Auto subscribe to this Stripe Plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.Plan')),
            ],
        ),
    ]
