# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:07
from __future__ import unicode_literals

import django_intenum
from django.db import migrations, models

import hsreplaynet.features.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', django_intenum.IntEnumField(choices=[(0, 'OFF'), (1, 'STAFF_ONLY'), (2, 'IN_PROGRESS'), (3, 'PUBLIC'), (4, 'AUTHORIZED_ONLY')], default=2, validators=[django_intenum.IntEnumValidator(hsreplaynet.features.models.FeatureStatus)])),
                ('read_only', models.BooleanField(default=False)),
            ],
        ),
    ]
