# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django_intenum
import hsreplaynet.features.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureInvite',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_count', models.PositiveIntegerField(default=0, editable=False, help_text='The amount of times this invitation has been successfully used.')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 for unlimited')),
                ('expires', models.DateTimeField(blank=True, help_text='No longer valid after this date.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=django_intenum.IntEnumField(choices=[(0, 'OFF'), (1, 'STAFF_ONLY'), (2, 'IN_PROGRESS'), (3, 'PUBLIC'), (4, 'AUTHORIZED_ONLY'), (5, 'LOGGED_IN_USERS')], default=2, validators=[django_intenum.IntEnumValidator(hsreplaynet.features.models.FeatureStatus)]),
        ),
        migrations.AddField(
            model_name='featureinvite',
            name='features',
            field=models.ManyToManyField(related_name='invites', to='features.Feature'),
        ),
    ]
