# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20170310_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureinvite',
            name='coupon',
            field=models.CharField(blank=True, help_text='Redeem a Stripe Coupon', max_length=500),
        ),
    ]
