# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_featureinvite_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureinvite',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
