# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 06:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_featureinvite_optional_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='rollout_percent',
            field=models.PositiveIntegerField(default=100, help_text='This may be set to a value lower than 100 to further restrict the user pool with access to this feature.', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
