# Generated by Django 2.0 on 2017-12-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_reflinks', '0001_initial'),
        ('djstripe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_auto_20171204_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='LazyDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField(null=True)),
                ('used', models.BooleanField(default=False)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Idempotency key to be used when applying the coupon.', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djstripe.Coupon')),
                ('referral_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.Referral')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lazy_discounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralLinkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_coupon', models.CharField(blank=True, max_length=255)),
                ('coupon_expiry', models.PositiveIntegerField(default=0)),
                ('referral_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='django_reflinks.ReferralLink')),
            ],
        ),
    ]
