# Generated by Django 2.0 on 2018-01-08 16:50

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		("billing", "0003_lazydiscount_referrallinkplan"),
	]

	operations = [
		migrations.CreateModel(
			name="CancellationRequest",
			fields=[
				(
					"id",
					models.AutoField(
						auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
					)
				),
				("subscription_id", models.CharField(max_length=255)),
				("reasons", django.contrib.postgres.fields.jsonb.JSONField()),
				("created", models.DateTimeField(auto_now_add=True)),
				("updated", models.DateTimeField(auto_now=True)),
				(
					"user",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE,
						related_name="cancellation_requests",
						to=settings.AUTH_USER_MODEL
					)
				),
			],
		),
	]
