# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 02:53
from __future__ import unicode_literals

from django.db import migrations


DROP_DECK_SUMMARY_STATS_TRIGGER = """
	DROP TRIGGER IF EXISTS maint_deck_summary_stats ON games_globalgameplayer;
"""

DROP_ARCHETYPE_STATS_TRIGGER_ON_GAMEREPLAY_TABLE = """
	DROP TRIGGER IF EXISTS maint_head_to_head_archetype_stats_trigger ON games_gamereplay;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20161128_1108'),
    ]

    operations = [
		migrations.RunSQL(
			DROP_DECK_SUMMARY_STATS_TRIGGER,
			None
		),
		migrations.RunSQL(
			DROP_ARCHETYPE_STATS_TRIGGER_ON_GAMEREPLAY_TABLE,
			None
		),
    ]
