# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_intenum
import hearthstone.enums


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20170201_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', django_intenum.IntEnumField(choices=[(0, 'FT_UNKNOWN'), (1, 'FT_WILD'), (2, 'FT_STANDARD')], default=2, validators=[django_intenum.IntEnumValidator(hearthstone.enums.FormatType)])),
                ('as_of', models.DateTimeField()),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.Archetype')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=0.0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signature_components', to='cards.Card')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cards.Signature')),
            ],
        ),
    ]
