# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hearthstone.enums
import hsreplaynet.utils.fields


DROP_IDX_CARDS_DECK_DIGEST_914F4A6C = """
DROP INDEX cards_deck_digest_914f4a6c_like;
"""


class Migration(migrations.Migration):

	dependencies = [
		('cards', '0007_auto_20161115_0738'),
	]

	operations = [
		migrations.AlterField(
			model_name='deck',
			name='digest',
			field=models.CharField(max_length=32, unique=True),
		),
		migrations.RunSQL(
			DROP_IDX_CARDS_DECK_DIGEST_914F4A6C,
			None
		),
	]
