# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:13
from __future__ import unicode_literals

from django.db import migrations


DROP_IDX_CARDS_INCLUDE_DBE7A8F6 = """
DROP INDEX cards_include_card_id_dbe7a8f6_like;
"""


class Migration(migrations.Migration):

	dependencies = [
		('cards', '0008_auto_20161121_2245'),
	]

	operations = [
		migrations.RunSQL(
			DROP_IDX_CARDS_INCLUDE_DBE7A8F6,
			None
		),
	]
