# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import hearthstone.enums
from django_intenum import IntEnumField, IntEnumValidator


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20161122_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='dbf_id',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='canonicaldeck',
            name='format',
            field=IntEnumField(choices=[(0, 'FT_UNKNOWN'), (1, 'FT_WILD'), (2, 'FT_STANDARD')], default=2, validators=[IntEnumValidator(hearthstone.enums.FormatType)]),
        ),
    ]
