# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('accounts', '0002_auto_20161128_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclaim',
            name='api_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.APIKey'),
        ),
        migrations.AlterField(
            model_name='accountclaim',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
