# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 00:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20161213_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
