# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='secret',
            field=models.CharField(blank=True, help_text='Salt for the X-Webhook-Signature header sent with the payload', max_length=255),
        ),
    ]
