# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_archetypetrainingdeck'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
