# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0004_auto_20170801_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archetype',
            old_name='active',
            new_name='active_in_standard',
        ),
        migrations.AddField(
            model_name='archetype',
            name='active_in_wild',
            field=models.BooleanField(default=False),
        ),
    ]
