# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_auto_20170827_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
    ]
