# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0009_auto_20170828_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersetsnapshot',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clustersetsnapshot',
            name='live_in_production',
            field=models.BooleanField(default=False),
        ),
    ]
