# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0011_clustersnapshot_data_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
