# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0013_auto_20170901_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='data_points',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
