# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 23:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0014_clustersnapshot_data_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersnapshot',
            name='ccp_signature',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
