# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0015_clustersnapshot_ccp_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='clustersetsnapshot',
            name='training_run_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
