# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 11:07
from __future__ import unicode_literals

import django_intenum
from django.db import migrations, models

import hsreplaynet.uploads.models
import hsreplaynet.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shortid', hsreplaynet.utils.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True, verbose_name='Short ID')),
                ('token_uuid', models.UUIDField(blank=True, db_column='token_id', null=True)),
                ('api_key_id', models.IntegerField(blank=True, db_column='api_key_id', null=True)),
                ('game_id', models.BigIntegerField(blank=True, db_column='game_id', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('upload_ip', models.GenericIPAddressField(null=True)),
                ('status', django_intenum.IntEnumField(default=0, enum=hsreplaynet.uploads.models.UploadEventStatus, db_index=True)),
                ('tainted', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('test_data', models.BooleanField(default=False)),
                ('canary', models.BooleanField(default=False)),
                ('metadata', models.TextField(blank=True)),
                ('file', models.FileField(null=True, upload_to=hsreplaynet.uploads.models._generate_upload_path)),
                ('user_agent', models.CharField(blank=True, max_length=100)),
                ('log_stream_name', models.CharField(blank=True, max_length=64)),
                ('log_group_name', models.CharField(blank=True, max_length=64)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
