# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20161128_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadevent',
            name='descriptor_data',
            field=models.TextField(blank=True),
        ),
    ]
