# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20170120_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redshiftstagingtrack',
            old_name='track_cleanup_at',
            new_name='track_cleanup_start_at',
        ),
        migrations.AddField(
            model_name='redshiftstagingtrack',
            name='track_cleanup_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='analyze_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='analyze_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='deduplication_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='duplicates_removed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='insert_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='insert_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='max_game_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='min_game_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='track_cleanup_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='track_cleanup_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='vacuum_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='vacuum_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
