# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 20:03
from __future__ import unicode_literals

import django_intenum
from django.db import migrations, models

import hsreplaynet.uploads.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_auto_20170125_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='redshiftstagingtrack',
            name='refreshing_view_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtrack',
            name='refreshing_view_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='is_materialized_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='refreshing_view_end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='refreshing_view_handle',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='refreshing_view_start_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='redshiftstagingtrack',
            name='stage',
            field=django_intenum.IntEnumField(default=1, enum=hsreplaynet.uploads.models.RedshiftETLStage),
        ),
        migrations.AlterField(
            model_name='redshiftstagingtracktable',
            name='stage',
            field=django_intenum.IntEnumField(default=1, enum=hsreplaynet.uploads.models.RedshiftETLStage),
        ),
    ]
