# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0008_auto_20170212_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='deduped_table_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='post_insert_table_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='redshiftstagingtracktable',
            name='pre_insert_table_size',
            field=models.IntegerField(null=True),
        ),
    ]
