# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_auto_20170213_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redshiftstagingtracktable',
            name='deduped_table_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='redshiftstagingtracktable',
            name='final_staging_table_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='redshiftstagingtracktable',
            name='post_insert_table_size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='redshiftstagingtracktable',
            name='pre_insert_table_size',
            field=models.BigIntegerField(null=True),
        ),
    ]
