# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('uploads', '0009_auto_20161015_0841'),
	]

	operations = [
		migrations.AlterField(
			model_name='uploadevent',
			name='api_key',
			field=models.IntegerField(blank=True, db_column='api_key_id', null=True),
		),
		migrations.AlterField(
			model_name='uploadevent',
			name='game',
			field=models.BigIntegerField(blank=True, db_column='game_id', null=True),
		),
		migrations.AlterField(
			model_name='uploadevent',
			name='token',
			field=models.UUIDField(blank=True, db_column='token_id', null=True),
		),
		migrations.RenameField('uploadevent', 'token', 'token_uuid'),
		migrations.RenameField('uploadevent', 'api_key', 'api_key_id'),
		migrations.RenameField('uploadevent', 'game', 'game_id'),
	]
